module:
  hugoVersion:
    min: "0.64.0"
  mounts:
  - source: partials
    target: layouts/partials/tnd-iubenda
  - source: shortcodes
    target: layouts/shortcodes
  - source: assets
    target: assets/tnd-iubenda